#!/usr/bin/python3
import requests
import os

url = 'http://127.0.0.1:9090/configs'
res = requests.get(url).json()
match res['mode']:
    case 'rule':
        r = requests.patch(url, json={'mode': 'direct'})
        print("direct")
    case 'direct':
        r = requests.patch(url, json={'mode': 'rule'})
        print("rule")
