mixed-port: 7890
mode: rule
ipv6: true
external-controller: 127.0.0.1:9090
external-ui: /usr/share/yacd/
log-level: warning

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true

proxies:
  - name: "socks"
    type: socks5
    server: 127.0.0.1
    port: 8022

proxy-groups:
  - name: dorm2free
    type: select
    proxies:
      - socks

rules:
  - IP-CIDR,127.0.0.0/8,DIRECT
  - MATCH,dorm2free
